repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
    - id: ruff
      args: [--fix]
      types_or: [python, pyi]
    - id: ruff-format
      types_or: [python, pyi]
- repo: https://github.com/astral-sh/uv-pre-commit
  # make sure uv.lock is up-to-date with pyproject.toml
  rev: 0.7.9
  hooks:
    - id: uv-lock
